/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
#ifndef ROOOPENUDID_AUTODEFS_H
#define ROOOPENUDID_AUTODEFS_H

/**
 * string name used to locate this extension
 */
#define S3E_EXT_ROOOPENUDID_NAME "rooOpenUDID"
#define S3E_EXT_ROOOPENUDID_HASH 0xa2e3bc2d

#endif /* !ROOOPENUDID_AUTODEFS_H */
